# Generated by Django 3.1.6 on 2021-04-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210427_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermodel',
            name='charisma',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='dexterity',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='intelligence',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='strength',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='wisdom',
            field=models.IntegerField(default=15),
        ),
    ]
