# Generated by Django 3.1.6 on 2021-04-29 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_auto_20210427_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermodel',
            name='charisma',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='dexterity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='intelligence',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='strength',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='wisdom',
            field=models.IntegerField(default=14),
        ),
    ]
